name: Deploy de la pagina
on:
  push:
      branches:
          - main
jobs:
  deploy-page:
    runs-on: ubuntu-last
    steps:
      - name: checkout
        uses: actions/checkput@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deplay-action@4.1.4
        with:
          branch: gh-pages
          folder: .

